name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR targeting the main branch

jobs:
  sonar:
    name: Run SonarQube analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can choose a different Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure your dependencies are listed in requirements.txt

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonarcloud-token: ${{ secrets.SONAR_TOKEN }}  # Use the token you created in SonarQube Cloud