name: SonarQube Analysis with Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  sonar:
    name: Run SonarQube analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonarcloud-token: ${{ secrets.S }}  
    - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml
    - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_SCANNER_TOKEN }}
    - name: Install Snyk CLI
      run: |
        npm install -g snyk
    - name: Test for vulnerabilities with Snyk
      run: |
        snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Snyk Monitor
      run: |
        snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  