name: SonarQube Analysis with Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=xml

    - name: Run SonarQube analysis
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        organization: your-sonarcloud-organization  # Add your SonarCloud organization
        projectKey: python-devops-pipeline
        projectName: Python DevOps Pipeline
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_SCANNER_TOKEN }}  # Set your SonarQube token in GitHub secrets

    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    - name: Test for vulnerabilities with Snyk
      run: |
        snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Set your Snyk token in GitHub secrets

    - name: Snyk Monitor
      run: |
        snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Set your Snyk token in GitHub secrets