name: SonarQube Analysis with Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  sonar:
    name: Run SonarQube analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonarcloud-token: ${{ secrets.S }}  
    - name: Run tests
        run: |
          pytest test_app.py
    - name: SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
      run: |
        # Install SonarScanner
        wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-4.7.0.2747-linux.zip
        unzip sonar-scanner-4.7.0.2747-linux.zip
        export PATH=$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH
        
        # Run the SonarQube scanner with the appropriate arguments
        sonar-scanner \
          -Dsonar.projectKey=python-devops-pipeline \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }
  